services:
  - type: web
    name: cafe307
    runtime: docker
    repo: https://github.com/vyzheng/cafe307
    envVars:
      - key: DATA_DIR
        value: /data
      - key: PRODUCTION_URL
        value: https://cafe307.com
    disk:
      name: cafe307-data
      mountPath: /data
      sizeGB: 1
