services:
  - type: web
    name: cafe307
    runtime: docker
    repo: https://github.com/vyzheng/cafe307
    envVars:
      - key: DATA_DIR
        value: /data
      - key: PRODUCTION_URL
        value: https://cafe307.com
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
    disk:
      name: cafe307-data
      mountPath: /data
      sizeGB: 1
